-- =====================================================
-- HuniOne — Seed Data Properti (untuk testing)
-- Cara pakai:
--   1. Buka https://supabase.com/dashboard → pilih project
--   2. SQL Editor → paste seluruh file ini → Run
--   3. Refresh halaman Explore (localhost:5173)
--
-- Data ini berstatus 'verified' agar tampil di ExplorePage
-- (query memakai .eq('status', 'verified')).
-- seller_id diambil dari user yang paling lama terdaftar (auth.users),
-- jadi PASTIKAN sudah ada minimal 1 user (login dulu sekali di aplikasi).
-- Catatan: menjalankan ulang akan INSERT duplikat.
-- =====================================================

insert into properties (
  seller_id,
  category,
  title,
  property_type,
  seller_whatsapp,
  description_id,
  address,
  city,
  district,
  price,
  bedrooms,
  bathrooms,
  area_sqm,
  certificate_status,
  image_url,
  status,
  created_at
) values
-- ============ DIJUAL (Rumah) ============
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Rumah Cluster Mewah 2 Lantai — BSD Green Valley',
  'Rumah',
  '081234567801',
  'Rumah 2 lantai di cluster eksklusif BSD dengan desain modern tropis. Lingkungan hijau, keamanan 24 jam, dekat dengan sekolah internasional dan pusat perbelanjaan.',
  'Kavling 12, BSD Green Valley, Pagedangan',
  'Tangerang Selatan',
  'Pagedangan',
  2850000000,
  4,
  3,
  150,
  'SHM',
  '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '2 days'
),
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Rumah Minimalis 1 Lantai — Griya Serpong Asri',
  'Rumah',
  '081234567802',
  'Rumah minimalis siap huni di kawasan Griya Serpong. Lokasi strategis 10 menit ke Exit Toll BSD, 15 menit ke pusat kota Tangerang Selatan.',
  'Jl. Asri Raya No. 8, Griya Serpong',
  'Tangerang Selatan',
  'Serpong',
  950000000,
  3,
  2,
  90,
  'SHGB',
  '["https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '20 days'
),
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Villa Pantai 3 Lantai — Anyer Beach Residence',
  'Villa',
  '081234567803',
  'Villa private 3 lantai menghadap pantai Anyer. Dilengkapi rooftop, kolam renang, dan 6 kamar tidur. Cocok untuk investasi penginapan atau tempat istirahat keluarga.',
  'Jl. Raya Karang Bolong KM 142, Anyer',
  'Serang',
  'Anyer',
  4200000000,
  6,
  5,
  380,
  'SHM',
  '["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '35 days'
),
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Rumah Hook Strategis — Bintaro Jaya Sektor 9',
  'Rumah',
  '081234567804',
  'Rumah hook corner dengan akses mudah ke JORR dan MRT. Sudah renovasi total, siap tinggal, ideal untuk keluarga besar.',
  'Sektor 9, Bintaro Jaya',
  'Tangerang Selatan',
  'Pondok Aren',
  3800000000,
  5,
  4,
  200,
  'SHM',
  '["https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '60 days'
),
-- ============ DIJUAL (Tanah) ============
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Tanah Kavling 200 m² — Citra Raya Cikupa',
  'Tanah',
  '081234567805',
  'Tanah kavling legal SHM di Citra Raya Cikupa. Lingkungan asri, dekat akses tol Jakarta-Merak dan fasilitas sekolah.',
  'Cluster Mutiara, Citra Raya',
  'Tangerang',
  'Cikupa',
  750000000,
  0,
  0,
  200,
  'SHM',
  '["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '45 days'
),
-- ============ DIJUAL (Apartemen) ============
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Apartemen Studio — Southgate Residence BSD',
  'Apartemen',
  '081234567806',
  'Apartemen studio fully furnished di Southgate Residence BSD. Fasilitas lengkap: kolam renang, gym, shuttle ke stasiun. ROI menarik untuk investasi.',
  'Tower B, Southgate Residence',
  'Tangerang Selatan',
  'BSD City',
  1200000000,
  1,
  1,
  32,
  'SHM Sarusun',
  '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '1 day'
),
-- ============ DISEWA (Apartemen / Kost) ============
(
  (select id from auth.users order by created_at limit 1),
  'Disewa',
  'Studio Apartemen 1 BR — Foresta BSD City',
  'Apartemen',
  '081234567807',
  'Sewa studio 1 bedroom di Foresta BSD, dekat AEON dan universitas. Furnished, AC, WiFi, dan listrik sudah termasuk.',
  'Foresta, BSD City',
  'Tangerang Selatan',
  'BSD City',
  4500000,
  1,
  1,
  36,
  'SHM Sarusun',
  '["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '3 days'
),
(
  (select id from auth.users order by created_at limit 1),
  'Disewa',
  'Kost Eksklusif Putri — Dekat Kampus UPH',
  'Kost',
  '081234567808',
  'Kost eksklusif khusus putri dengan fasilitas AC, WiFi kencang, laundry, dan dapur bersama. 5 menit ke kampus UPH, harga sudah termasuk air dan listrik.',
  'Dekat Kampus UPH, Alam Sutera',
  'Tangerang',
  'Serpong Utara',
  2500000,
  1,
  1,
  24,
  'SPPT',
  '["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '5 days'
),
(
  (select id from auth.users order by created_at limit 1),
  'Disewa',
  'Kos Putra Murah — 5 Menit ke Kampus',
  'Kost',
  '081234567809',
  'Kos putra harga mahasiswa dengan kamar mandi dalam, kasur dan meja belajar. Cocok untuk mahasiswa baru, bebas biaya administrasi.',
  'Jl. Melati Raya, Ciputat',
  'Tangerang Selatan',
  'Ciputat',
  1200000,
  1,
  1,
  18,
  'SPPT',
  '["https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '10 days'
),
-- ============ DISEWA (Kantor / Ruko) ============
(
  (select id from auth.users order by created_at limit 1),
  'Disewa',
  'Ruko 2 Lantai — Rukan CBD BSD Central',
  'Ruko',
  '081234567810',
  'Ruko 2 lantai siap pakai di Rukan CBD BSD Central. Depan jalan raya, ramai, cocok untuk kantor, klinik, atau kafe. Ada 1 ruang parkir.',
  'Rukan CBD, BSD Central',
  'Tangerang Selatan',
  'BSD City',
  15000000,
  2,
  2,
  96,
  'SHGB',
  '["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '15 days'
),
(
  (select id from auth.users order by created_at limit 1),
  'Disewa',
  'Ruang Kantor 2 Lantai — Menara Teknologi Jakarta',
  'Kantor',
  '081234567811',
  'Ruang kantor siap pakai 2 lantai di Menara Teknologi, Kuningan. Konsep open space, sudah ada partisi dan ruang meeting. Minimum sewa 1 tahun.',
  'Jl. HR Rasuna Said, Kuningan',
  'Jakarta Selatan',
  'Setiabudi',
  35000000,
  0,
  2,
  160,
  'SHGB',
  '["https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '7 days'
),
-- ============ DISEWA (Rumah) ============
(
  (select id from auth.users order by created_at limit 1),
  'Disewa',
  'Rumah 2 Lantai Furnished — Gandaria Jakarta Selatan',
  'Rumah',
  '081234567812',
  'Rumah 2 lantai fully furnished di kawasan Gandaria. AC semua kamar, ada carport 2 mobil. Strategis dekat dengan sekolah dan mall.',
  'Jl. Gandaria Tengah, Kebayoran Baru',
  'Jakarta Selatan',
  'Kebayoran Baru',
  25000000,
  3,
  3,
  140,
  'SHM',
  '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '40 days'
),
-- ============ DIJUAL (Rumah, contoh status lama untuk tab "Baru") ============
(
  (select id from auth.users order by created_at limit 1),
  'Dijual',
  'Rumah Second Siap Huni — Cibubur Residence',
  'Rumah',
  '081234567813',
  'Rumah second siap huni di Cibubur Residence dengan SHM. Sudah renovasi dapur dan kamar mandi, bebas banjir, dekat pintu tol.',
  'Cibubur Residence, Cibubur',
  'Jakarta Timur',
  'Ciracas',
  1450000000,
  3,
  2,
  100,
  'SHM',
  '["https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80"]',
  'verified',
  now() - interval '90 days'
);
